// GENERATED by tool/sync_twemoji.sh, do not edit by hand.

/// The upstream repository the bundled Twemoji assets were taken from.
const String twemojiSourceRepository = 'https://github.com/jdecked/twemoji';

/// The upstream Twemoji release the bundled assets were taken from.
const String twemojiVersion = '17.0.3';
