#!/usr/bin/env bash
#
# Syncs the bundled Twemoji assets (and the emoji regex) with an upstream
# release of jdecked/twemoji, the actively maintained successor of the
# now-dormant twitter/twemoji.
#
# Usage:
#   tool/sync_twemoji.sh [options]
#
#   --ref <tag>       Twemoji tag to sync (default: the newest upstream tag).
#   --skip-regex      Only sync assets, leave lib/src/utils.dart alone.
#   --print-current   Print the currently bundled Twemoji version and exit.
#   --print-latest    Print the newest upstream Twemoji tag and exit.
#
# Environment:
#   TWEMOJI_REPO      Upstream repository (default: jdecked/twemoji).

set -euo pipefail

TWEMOJI_REPO="${TWEMOJI_REPO:-https://github.com/jdecked/twemoji.git}"

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
assets_dir="$root_dir/assets"
version_file="$root_dir/lib/src/twemoji_version.dart"

die() {
  echo "error: $*" >&2
  exit 1
}

usage() {
  sed -n '3,17p' "${BASH_SOURCE[0]}" | sed 's|^# \{0,1\}||'
}

current_version() {
  sed -n "s|^const String twemojiVersion = '\(.*\)';|\1|p" "$version_file"
}

latest_ref() {
  git ls-remote --tags --refs "$TWEMOJI_REPO" \
    | awk '{print $2}' \
    | sed 's|refs/tags/||' \
    | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' \
    | sort -V \
    | tail -n 1
}

write_version_file() {
  local version="$1" repo_url="${TWEMOJI_REPO%.git}"
  cat > "$version_file" <<DART_EOF
// GENERATED by tool/sync_twemoji.sh, do not edit by hand.

/// The upstream repository the bundled Twemoji assets were taken from.
const String twemojiSourceRepository = '$repo_url';

/// The upstream Twemoji release the bundled assets were taken from.
const String twemojiVersion = '$version';
DART_EOF
}

emit_output() {
  if [ -n "${GITHUB_OUTPUT:-}" ]; then
    echo "$1=$2" >> "$GITHUB_OUTPUT"
  fi
}

ref=""
skip_regex=0

while [ $# -gt 0 ]; do
  case "$1" in
    --ref)
      [ $# -ge 2 ] || die "missing value for --ref"
      ref="$2"
      shift 2
      ;;
    --skip-regex)
      skip_regex=1
      shift
      ;;
    --print-current)
      current_version
      exit 0
      ;;
    --print-latest)
      latest_ref
      exit 0
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

if [ -z "$ref" ]; then
  ref="$(latest_ref)"
  [ -n "$ref" ] || die "could not determine the latest tag of $TWEMOJI_REPO"
fi
version="${ref#v}"

work_dir="$(mktemp -d)"
trap 'rm -rf "$work_dir"' EXIT

echo "Cloning $TWEMOJI_REPO at $ref"
git clone --quiet -c advice.detachedHead=false --depth 1 --branch "$ref" "$TWEMOJI_REPO" "$work_dir/twemoji" \
  || die "could not clone $TWEMOJI_REPO at $ref"

src_png="$work_dir/twemoji/assets/72x72"
src_svg="$work_dir/twemoji/assets/svg"
[ -d "$src_png" ] || die "$ref has no assets/72x72 directory"
[ -d "$src_svg" ] || die "$ref has no assets/svg directory"

png_count="$(find "$src_png" -name '*.png' | wc -l)"
svg_count="$(find "$src_svg" -name '*.svg' | wc -l)"
# Guards against silently wiping the bundled assets if upstream ever moves them.
[ "$png_count" -gt 1000 ] || die "only $png_count PNGs found in $ref, refusing to sync"
[ "$svg_count" -gt 1000 ] || die "only $svg_count SVGs found in $ref, refusing to sync"

# Recreate the directories from scratch so emojis dropped upstream disappear
# here as well.
rm -rf "$assets_dir/png" "$assets_dir/svg"
mkdir -p "$assets_dir/png" "$assets_dir/svg"
cp "$src_png"/*.png "$assets_dir/png/"
cp "$src_svg"/*.svg "$assets_dir/svg/"

write_version_file "$version"

echo "Synced $png_count PNGs and $svg_count SVGs from Twemoji $ref"

if [ "$skip_regex" -eq 0 ]; then
  command -v node > /dev/null || die "node is required to regenerate the emoji regex (use --skip-regex to skip)"
  # The regex comes from `@misskey-dev/emoji-data`, not from the clone above:
  # see the header of tool/update_emoji_regex.mjs for why.
  node "$root_dir/tool/update_emoji_regex.mjs" --twemoji-version "$version"
fi

emit_output ref "$ref"
emit_output version "$version"
emit_output png_count "$png_count"
emit_output svg_count "$svg_count"
